---
title: "analysis"
author: "A.J. Brown"
date: "`r Sys.Date()`"
output: html_document
---
# Sampler Comparison Analysis Using Bayesian Inference
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include=FALSE}
# load libraries
library(rethinking)
library(dplyr)
library(tidyr)
```

## Data Import and Preparation
```{r}
# load simulated data for testing
# note that this script places the working directory in the 2_code folder, not the root of the project
d <- read.csv("../1_data/sim_data.csv")

# standardize analytes
d <- d %>%
  group_by(analyte_abbr) %>%
  mutate(result_ctr = standardize(result)) %>%
  ungroup()

# parse data into sub dataframes for each analyte_abbr
d_list <- split(d, d$analyte_abbr)
# dat <- d_list$NO3
# dat <- d_list$NO2
# dat <- d_list$TKN
# dat <- d_list$TP
# dat <- d_list$OP
# dat <- d_list$TSS
# dat <- d_list$EC
# dat <- d_list$pH
# dat <- d_list$TDS

# our model uses all data at once, no need to split
dat <- d

```

## Model Generation

```{r}
# create data list for ulam models
dlist <- list(
    C_obs = dat$result_ctr, #use standardized results
    #C_sd = d$Divorce.SE / sd( d$Divorce ), # we don't have SE from our sample
    S = as.numeric(as.factor(dat$method.name)),
    TRT = as.numeric(as.factor(dat$treatment)),
    I = as.numeric(as.factor(dat$event.count)),
    A = as.numeric(as.factor(dat$analyte_abbr)),
    B = as.numeric(as.factor(dat$block)),
    N = nrow(dat)
)
```

```{r, eval=FALSE, echo=FALSE}
# fit model 1.0, simple model with no partial pooling
m1.0 <- ulam(
    alist(
        # model for C* (observed results)
        C_obs ~ dnorm(mu, sigma),
        sigma ~ dexp(1),
        # model
        mu <- a + bS[S] + bTRT[TRT],
        # regular priors
        a ~ dnorm(0,0.2),
        bS[S] ~ dnorm(0,0.5),
        bTRT[TRT] ~ dnorm(0,0.5),
        bA[A] ~ dnorm(0,0.5)
        
        
    ) , data=dlist , chains=4 , cores=4 )
```

```{r, eval=FALSE, echo=FALSE}
# fit model 2.0, 
# using partial pooling around irrigation # (centered)

m2.0 <- ulam(
    alist(
        # model for C* (observed results)
        C_obs ~ dnorm(mu, sigma),
        sigma ~ dexp(1),
        
        mu <- a[I] + bA[A] + bS[S] + bTRT[TRT],
        # regular priors
        bS[S] ~ dnorm(0,0.5),
        bTRT[TRT] ~ dnorm(0,0.5),
        bA[A] ~ dnorm(0,0.5),
        # adaptive priors
        a[I] ~ dnorm(a_bar, sigma_a),
        # hyper-priors
        a_bar ~ dnorm(0,0.5),
        sigma_a ~ dexp(1)
        
    ), data=dlist , chains=4 , cores=4)
```

```{r, eval=FALSE, echo=FALSE}
# fit model 2.1, 
# using partial pooling around irrigation # and Analyte (centered)

m2.1 <- ulam(
    alist(
        # model for C* (observed results)
        C_obs ~ dnorm(mu, sigma),
        sigma ~ dexp(1),
        
        mu <- a[I] + g[A] + bS[S] + bTRT[TRT],
        # regular priors
        bS[S] ~ dnorm(0,0.5),
        bTRT[TRT] ~ dnorm(0,0.5),
        # adaptive priors
        a[I] ~ dnorm(a_bar, sigma_a),
        g[A] ~ dnorm(g_bar, sigma_g),
        # hyper-priors
        a_bar ~ dnorm(0,0.5),
        g_bar ~ dnorm(0,0.5),
        sigma_a ~ dexp(1),
        sigma_g ~ dexp(1)
        
    ), data=dlist , chains=4 , cores=4)
```

```{r}
# fit model 2.2
# using partial pooling around irrigation # and Analyte (non-centered)
m2.2 <- ulam(
    alist(
        # model for C* (observed results)
        C_obs ~ dnorm(mu, sigma),
        sigma ~ dexp(1),
        # model
        mu <- a_bar + 
              z[I]*sigma_a + # irrigation intercepts
              x[A]*sigma_g + # analyte intercepts
              bS[S] + # sampler method effect
              bTRT[TRT], # treatment effect
        # regular priors
        a_bar ~ dnorm(0,0.5),
        bS[S] ~ dnorm(0,0.5),
        bTRT[TRT] ~ dnorm(0,0.5),
        z[I] ~ dnorm(0,1),
        x[A] ~ dnorm(0,1),
        sigma_a ~ dexp(1),
        sigma_g ~ dexp(1),
        gq> vector[I]:a <<- a_bar + z*sigma_a,
        gq> vector[A]:g <<- x*sigma_g
        # adaptive priors
        # none
        # hyper-priors
        # none
        
    ), data=dlist , chains=4 , cores=4 )
```

```{r}
# fit model 2.3
# using partial pooling around irrigation # and Analyte, and block (non-centered)
m2.3 <- ulam(
    alist(
        # model for C* (observed results)
        C_obs ~ dnorm(mu, sigma),
        sigma ~ dexp(1),
        # model
        mu <- a_bar + 
              z[I]*sigma_a + # irrigation intercepts
              x[A]*sigma_g + # analyte intercepts
              b[B]*sigma_j + # block intercepts
              bS[S] + # sampler method effect
              bTRT[TRT], # treatment effect
        # regular priors
        a_bar ~ dnorm(0,0.5),
        bS[S] ~ dnorm(0,0.5),
        bTRT[TRT] ~ dnorm(0,0.5),
        z[I] ~ dnorm(0,1),
        x[A] ~ dnorm(0,1),
        b[B] ~ dnorm(0,1),
        sigma_a ~ dexp(1),
        sigma_g ~ dexp(1),
        sigma_j ~ dexp(1),
        gq> vector[I]:a <<- a_bar + z*sigma_a,
        gq> vector[A]:g <<- x*sigma_g,
        gq> vector[TRT]:j <<- b*sigma_j
        # adaptive priors
          # none
        # hyper-priors
          # none
        
    ), data=dlist, chains=4, cores=4 )
```

```{r, eval=FALSE, echo=FALSE}
# fit model 3.0
# treating C_true as unobserved data
# partial pooling around irrigation # and analyte
# non-centered

m3.0 <- ulam(
    alist(
        # model for C* (observed results)
        C_obs ~ dnorm(C_true, C_sd),
        C_sd ~ dexp(1), # need a prior for C_sd
        
        # model for D (unobserved)
        vector[N]:C_true ~ dnorm(mu , sigma),
        mu <- a_bar + 
              z[I]*sigma_a + # irrigation intercepts
              x[A]*sigma_g + # analyte intercepts
              bS[S] + # sampler method effect
              bTRT[TRT], # treatment effect
        # regular priors
        sigma ~ dexp(1),
        a_bar ~ dnorm(0,0.5),
        bS[S] ~ dnorm(0,0.5),
        bTRT[TRT] ~ dnorm(0,0.5),
        z[I] ~ dnorm(0,1),
        x[A] ~ dnorm(0,1),
        sigma_a ~ dexp(1),
        sigma_g ~ dexp(1),
        gq> vector[I]:a <<- a_bar + z*sigma_a,
        gq> vector[A]:g <<- x*sigma_g
        
    ) , data=dlist , chains=4 , cores=4)
```

## Model Summaries
```{r, eval=FALSE, echo=FALSE}
# model 1.0 - no partial pooling by irrigation
precis(m1.0 , depth=2)
plot(precis(m1.0 , depth=2))
```

```{r, eval=FALSE, echo=FALSE}
# model 2.0 - centered
precis(m2.0 , depth=2)
plot(precis(m2.0 , depth=2))
```

```{r, eval=FALSE, echo=FALSE}
# model 2.1 - centered with analyte pooling
precis(m2.1 , depth=2)
plot(precis(m2.1 , depth=2))
```

```{r}
# model 2.2 - non-centered 2.1
precis(m2.2, depth=2)
plot(precis(m2.2, depth=2))
```

```{r}
# model 2.3
precis(m2.3, depth=2)
plot(precis(m2.3, depth=2))
```

```{r, eval=FALSE, echo=FALSE}
# model 3.0 - true value unobserved
precis(m3.0 , depth=2)
#plot(precis(m3.0 , depth=2))
```

## Graphing Results
```{r}
# extract posterior predictions
#post <- extract.samples(m1.0)
#post <- extract.samples(m2.0)
#post <- extract.samples(m2.1)
#post <- extract.samples(m2.2)
post <- extract.samples(m2.3)
#post <- extract.samples(m3.0)

# make dataframes
bS_df <- as.data.frame(post$bS)

bTRT_df <- as.data.frame(post$bTRT)
```

### Effect of Sample Method
```{r}
# plot effect of S
dens(bS_df$V1, lwd=4, col=2, xlab="bS (Effect of Sample Method)") # Red: Grab Sample
dens(bS_df$V2, lwd=4, col=4, xlab="bS (Effect of Sample Method)", add=TRUE) # Blue: Hourly Grab
dens(bS_df$V3, lwd=4, col=6, xlab="bS (Effect of Sample Method)", add=TRUE) # Purple: ISCO
dens(bS_df$V4, lwd=4, col=8, xlab="bS (Effect of Sample Method)", add=TRUE) # Gray: Low-Cost Sampler
abline(v=0,lty=3)

# Define the range for x_seq based on the values in bS_df
x_seq <- seq(from = min(bS_df) - 1, to = max(bS_df) + 1, length.out = 300)

# Calculate the prior density
prior_dens <- dnorm(x_seq, mean = 0, sd = 0.5)

# Add the prior distribution to the plot
lines(x_seq, prior_dens, lwd = 2, col = "black", lty = 2)
```

### Effect of Tillage
```{r}
# plot effect of TRT
dens(bTRT_df$V1, lwd=4, col=2, xlab="bS (Effect of Tillage)") # Red: CT
dens(bTRT_df$V2, lwd=4, col=4, xlab="bS (Effect of Tillage)", add=TRUE) # Blue: MT
dens(bTRT_df$V3, lwd=4, col=6, xlab="bS (Effect of Tillage)", add=TRUE) # Purple: ST
abline(v=0,lty=3)

# Define the range for x_seq based on the values in bTRT_df
x_seq <- seq(from = min(bTRT_df) - 1, to = max(bTRT_df) + 1, length.out = 300)

# Calculate the prior density
prior_dens <- dnorm(x_seq, mean = 0, sd = 0.5)

# Add the prior distribution to the plot
lines(x_seq, prior_dens, lwd = 2, col = "black", lty = 2)

```

### Analyte Prediction
```{r}
# make legends for clusters and factors
# Function to generate and print legend for a given column
generate_legend <- function(data, column_name) {
  factor_version <- as.factor(data[[column_name]])
  legend <- setNames(as.character(levels(factor_version)), seq_along(levels(factor_version)))
  cat("\nLegend for", column_name, ":\n")
  print(legend)
}

# Your data frame: dat
# Specify columns for which to generate legends
columns_to_process <- c("analyte_abbr", "event.count", "method.name", "treatment")

# Loop through the specified columns and generate+print legends
for(column_name in columns_to_process) {
  generate_legend(dat, column_name)
}

```


```{r}
# plot analytes concentration by sample method

# create analyte list for transforming in function later
analyte_list <- levels(factor(dat$analyte_abbr))

# create link function to extract specific predictions
p_link <- function(posterior_samples, I=1, A=1, S=1, TRT=1) {
  mu <- with(posterior_samples,
             a[,I] + g[,A] + bS[,S] + bTRT[,TRT]) # model 2.2
             #a[,I] + bA[,A] + bS[,S] + bTRT[,TRT]) # model 2.0
             #a[,I] + bS[,S] + bTRT[,TRT]) # model 1.0
  # convert back to real units
  mu_analyte <- mean(d_list[[analyte_list[[A]]]]$result)
  sigma_analyte <- sd(d_list[[analyte_list[[A]]]]$result)
  real_mu <- mu * sigma_analyte + mu_analyte
  return(real_mu)
}

p_raw <- sapply(1:4, function(i) p_link(posterior_samples=post, I=2, A=9, S=i, TRT=1))
p_mu <- apply(p_raw, 2, mean)
p_ci <- apply(p_raw, 2, PI)
print ("1) Grab Sample, 2) Hourly Grab, 3) ISCO, 4) Low-Cost Sampler")
p_mu
p_ci
```


```{r}
calculate_and_print_means_by_treatment <- function(data) {
  # Get unique levels of treatment
  treatment_levels <- unique(data$treatment)
  
  # Iterate over each treatment level
  for(trt in treatment_levels) {
    cat("\nMean Results Table for Treatment:", trt, "\n")
    
    mean_results_table <- data %>%
      filter(treatment == trt) %>%
      group_by(analyte_abbr, method.name) %>%
      summarise(mean_result = mean(result, na.rm = TRUE), .groups = 'drop') %>%
      pivot_wider(names_from = method.name, values_from = mean_result) 
    
    # Print the table for the current treatment level
    print(mean_results_table)
  }
}

# Assuming 'd' is your data frame
calculate_and_print_means_by_treatment(d)
```

